### ISSUE TITLE
Encounter errors when running test_type1.py

### ISSUE THREAD

**Issue by wangchuan** [lllcho/CAPTCHA-breaking#2]
I have configured the environment as the instruction told, but still encountered the following error which I am unable to fix.

```
Traceback (most recent call last):
  File "./test_type1.py", line 35, in <module>
    model_ch.compile(loss='categorical_crossentropy', optimizer='adagrad')
  File "build/bdist.linux-x86_64/egg/keras/models.py", line 351, in compile
  File "build/bdist.linux-x86_64/egg/keras/layers/containers.py", line 53, in get_output
  File "build/bdist.linux-x86_64/egg/keras/layers/core.py", line 388, in get_output
  File "build/bdist.linux-x86_64/egg/keras/layers/core.py", line 32, in get_input
  File "build/bdist.linux-x86_64/egg/keras/layers/core.py", line 228, in get_output
  File "build/bdist.linux-x86_64/egg/keras/layers/core.py", line 32, in get_input
  File "build/bdist.linux-x86_64/egg/keras/layers/core.py", line 388, in get_output
  File "build/bdist.linux-x86_64/egg/keras/layers/core.py", line 32, in get_input
  File "build/bdist.linux-x86_64/egg/keras/layers/core.py", line 309, in get_output
  File "build/bdist.linux-x86_64/egg/keras/layers/core.py", line 32, in get_input
  File "build/bdist.linux-x86_64/egg/keras/layers/core.py", line 228, in get_output
  File "build/bdist.linux-x86_64/egg/keras/layers/core.py", line 32, in get_input
  File "build/bdist.linux-x86_64/egg/keras/layers/convolutional.py", line 209, in get_output
  File "build/bdist.linux-x86_64/egg/keras/layers/core.py", line 32, in get_input
  File "build/bdist.linux-x86_64/egg/keras/layers/convolutional.py", line 168, in get_output
  File "build/bdist.linux-x86_64/egg/keras/layers/core.py", line 32, in get_input
  File "build/bdist.linux-x86_64/egg/keras/layers/convolutional.py", line 168, in get_output
  File "build/bdist.linux-x86_64/egg/keras/layers/core.py", line 32, in get_input
  File "build/bdist.linux-x86_64/egg/keras/layers/core.py", line 228, in get_output
  File "build/bdist.linux-x86_64/egg/keras/layers/core.py", line 32, in get_input
  File "build/bdist.linux-x86_64/egg/keras/layers/convolutional.py", line 210, in get_output
AttributeError: 'module' object has no attribute 'downsample'

```

**Comment by lllcho** [comment]
这个问题应该是theano没配置好的原因，确保你把之前的theano(keras)都完全卸载了，然后使用提供的Anaconda下载链接，这个里面自带有theano，或者单独安装所需python包也可以，只要使用相同版本的theano就好。

**Comment by wangchuan** [comment]
请问您用的是哪个版本的theano? 我运行`theano.test()`显示我的版本是`theano-0.8.1-version`。另外我装的Anaconda是官方最新版本，keras安装的是您代码里提供的`keras-master`.

**Comment by lllcho** [comment]
theano-0.7.1，0.70应该也可以的，theano-0.8以后的应该都会有这个问题

**Comment by wangchuan** [comment]
好的，谢谢，我已经可以run你的code。我发现你提供的数据测试精确度确实很高，但我如果自己找别的例子就很不好（比如，仿照你type5中英文字母的例子，我也找了类似的，只是字体可能不太一样），我想可能是因为你的模型都是针对某种数据训练好的，所以别的数据就不行。所以请问，在你们训练数据的时候，这些数据的ground truth result是如何得来的？人工标会很累吧？并且我发现你共享的百度盘数据里也只有图片没有label，故请教这个问题。

**Comment by lllcho** [comment]
网盘共享的都是测试数据（我也没标签）。训练数据每种type有2w样本（标签由竞赛主办方提供，他们有生成每种验证码的代码），我的模型就是使用所提供的2w个验证码训练得到的。如果你要用在其他验证码上的话，即使只是细微差别也应该重新训练模型，因为有差别就说明样本不是来自同一分布。这里我的识别方法可供参考。
